version: "3"
services:
  web:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 80:80
    links:
      - "db"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
      - MYSQL_DATABASE=abc
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPASS}
    ports:
      - 8080:80
    links:
      - "db"